# Generated by Django 6.0.1 on 2026-02-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram')),
                ('cargo_type', models.CharField(max_length=200, verbose_name='Тип груза')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
        ),
    ]
